"""Production driver: dispatch a federation to remote Globus Compute endpoints.

A thin wrapper over APPFL's own round loop. The logic is APPFL's; what this adds is the
operational scaffolding a real run needs and a bare script does not:

* the compat shim applied before APPFL is imported (see core/compat.py)
* thread caps set for the driver process, not only the workers
* per-round, per-client progress that names the site rather than the endpoint UUID
* failures translated into the thing to actually go check

Configs are generated by ``appfl-bio-suite run``; this is not normally invoked directly.
"""

from __future__ import annotations

import argparse
import os
import pprint
import sys
from concurrent.futures import Future

# Before APPFL. appfl 1.10.0 imports a globus-compute-sdk module that 4.9.0 removed, and
# this suite pins both.
import appfl_bio_suite  # noqa: F401


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--server-config", required=True)
    parser.add_argument("--client-config", required=True)
    parser.add_argument(
        "--get-sample-size",
        action="store_true",
        help="Ask each client its sample count first. Required for "
        "client_weights_mode: sample_size; costs one extra round trip per site.",
    )
    parser.add_argument(
        "--watch",
        default=None,
        help="Path to the watch sidecar written by `run --watch`. Streams this run onto "
        "the federation map. Absent, or unreadable, the run proceeds unwatched.",
    )
    args = parser.parse_args(argv)

    # The driver imports numpy too, and a shared login node's thread budget does not
    # care that this process is not a worker.
    for var in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS"):
        os.environ.setdefault(var, "1")

    from appfl.agent import ServerAgent
    from appfl.comm.globus_compute import GlobusComputeServerCommunicator
    from omegaconf import OmegaConf

    from appfl_bio_suite.core.watch import RunWatcher, watchable

    server_config = OmegaConf.load(args.server_config)
    client_configs = OmegaConf.load(args.client_config)["clients"]

    server_agent = ServerAgent(server_agent_config=server_config)
    log = server_agent.logger

    rounds = server_config.server_configs.num_global_epochs
    log.info(f"[setup] {len(client_configs)} client(s), {rounds} global round(s)")

    # Endpoint UUIDs are what APPFL keys results by; nobody thinks in UUIDs.
    site_names = {c["endpoint_id"]: c.get("client_id", c["endpoint_id"]) for c in client_configs}

    def site(endpoint_id: str) -> str:
        return site_names.get(endpoint_id, endpoint_id)

    watcher = RunWatcher.load(args.watch)
    watcher.start(
        algorithm=str(server_config.server_configs.get("scheduler", "SyncScheduler")),
        config={
            "rounds": int(rounds),
            "sites": len(client_configs),
            "driver": "globus_compute",
        },
    )

    try:
        communicator = GlobusComputeServerCommunicator(
            server_agent_config=server_agent.server_agent_config,
            client_agent_configs=client_configs,
            logger=log,
        )
    except Exception as exc:
        from appfl_bio_suite.core.endpoint import explain_submit_failure

        log.error(f"[setup] could not connect: {type(exc).__name__}: {exc}")
        log.error(explain_submit_failure(exc))
        watcher.finish()
        return 1

    try:
        if args.get_sample_size:
            log.info("[setup] requesting sample sizes")
            communicator.send_task_to_all_clients(task_name="get_sample_size")
            for endpoint_id, payload in communicator.recv_result_from_all_clients()[1].items():
                server_agent.set_sample_size(endpoint_id, payload["sample_size"])
                log.info(f"[setup] {site(endpoint_id)}: n = {payload['sample_size']}")

        log.info("[train] dispatching round 1 to all clients")
        init_model = server_agent.get_parameters(globus_compute_run=True)
        if isinstance(init_model, tuple):
            init_model, metadata = init_model
        else:
            metadata = {}

        communicator.send_task_to_all_clients(
            task_name="train", model=init_model, metadata=metadata, need_model_response=True
        )

        futures: dict[str, Future] = {}
        client_rounds: dict[str, int] = {}
        # Rounds close when every site has reported them. Under an asynchronous
        # scheduler sites are on different rounds at the same instant, so a round is not
        # a moment in the driver's control flow and cannot be closed by position in the
        # loop; counting arrivals is the only definition that holds for both schedulers.
        round_arrivals: dict[int, int] = {}
        watcher.round_start(1)

        while not server_agent.training_finished():
            endpoint_id, client_model, client_metadata = communicator.recv_result_from_one_client()
            client_rounds[endpoint_id] = client_rounds.get(endpoint_id, 0) + 1
            this_round = client_rounds[endpoint_id]
            log.info(
                f"[train] {site(endpoint_id)} returned round "
                f"{this_round}/{rounds}\n"
                f"{pprint.pformat(client_metadata)}"
            )

            watcher.client_update(endpoint_id, this_round, **watchable(client_metadata))
            round_arrivals[this_round] = round_arrivals.get(this_round, 0) + 1
            if round_arrivals[this_round] == len(client_configs):
                watcher.round_end(this_round)
                watcher.round_start(this_round + 1)

            global_model = server_agent.global_update(endpoint_id, client_model, **client_metadata)

            if isinstance(global_model, Future):
                futures[endpoint_id] = global_model
            else:
                _dispatch_next(
                    communicator,
                    server_agent,
                    log,
                    site,
                    endpoint_id,
                    global_model,
                    client_rounds[endpoint_id],
                )

            for done_id in [eid for eid, f in futures.items() if f.done()]:
                _dispatch_next(
                    communicator,
                    server_agent,
                    log,
                    site,
                    done_id,
                    futures.pop(done_id).result(),
                    client_rounds[done_id],
                )
    except KeyboardInterrupt:
        log.warning("[train] interrupted; cancelling outstanding tasks")
        return 130
    except Exception as exc:
        from appfl_bio_suite.core.endpoint import explain_submit_failure

        log.error(f"[train] failed: {type(exc).__name__}: {exc}")
        log.error(explain_submit_failure(exc))
        return 1
    finally:
        watcher.finish()
        try:
            communicator.cancel_all_tasks()
            communicator.shutdown_all_clients()
        except Exception:  # noqa: BLE001 - shutdown must not mask the real error
            pass

    log.info("Federated Learning Training Completed!")
    log.info(f"[done] results in {server_config.server_configs.logging_output_dirname}")
    return 0


def _dispatch_next(communicator, server_agent, log, site, endpoint_id, global_model, round_no):
    if isinstance(global_model, tuple):
        global_model, metadata = global_model
    else:
        metadata = {}
    metadata["round"] = round_no
    if server_agent.training_finished():
        return
    communicator.send_task_to_one_client(
        endpoint_id,
        task_name="train",
        model=global_model,
        metadata=metadata,
        need_model_response=True,
    )
    log.info(f"[train] sent updated global model to {site(endpoint_id)}")


if __name__ == "__main__":
    sys.exit(main())
